// Typelizer digest 95bce86b90b9a4ea5ea62044c196da87
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /settings/team */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/team', {}, options),
    method: 'get',
  }),

  /** POST /settings/team */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/settings/team', {}, options),
    method: 'post',
  }),
}
