// Typelizer digest 43acc8a8a1bf9dce19fe8373868983a0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /settings/workspace */
  show: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/settings/workspace', {}, options),
    method: 'get',
  }),

  /** PATCH /settings/workspace */
  update: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/settings/workspace', {}, options),
    method: 'patch',
  }),
}
