services:
  db:
    image: postgres:18.4
    environment:
      POSTGRES_DB: teplotec_development
      POSTGRES_USER: teplotec
      POSTGRES_PASSWORD: teplotec_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teplotec -d teplotec_development"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
