service: teplotec_installer
image: teplotec_installer

servers:
  web:
    - 192.168.0.1

registry:
  server: localhost:5555

env:
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_URL
    - CACHE_DATABASE_URL
    - QUEUE_DATABASE_URL
    - CABLE_DATABASE_URL
  clear:
    SOLID_QUEUE_IN_PUMA: true

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbc: app exec --interactive --reuse "bin/rails dbconsole --include-password"

volumes:
  - "teplotec_installer_storage:/rails/storage"

asset_path: /rails/public

builder:
  arch: amd64
  cache:
    type: registry
    image: your-user/teplotec-installer-build-cache
    options: mode=max
