// Typelizer digest 69572c624b9c26b128970a84fec6e71b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /candidates */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/candidates', {}, options),
    method: 'get',
  }),

  /** POST /candidates */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/candidates', {}, options),
    method: 'post',
  }),

  /** GET /candidates/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/candidates/new', {}, options),
    method: 'get',
  }),

  /** GET /candidates/:id/edit */
  edit: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/candidates/:id/edit', params, options),
    method: 'get',
  }),

  /** GET /candidates/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/candidates/:id', params, options),
    method: 'get',
  }),

  /** PATCH /candidates/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/candidates/:id', params, options),
    method: 'patch',
  }),
}
