// Typelizer digest a1ae915048c84c87ac474a93828f1504
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /client_companies */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/client_companies', {}, options),
    method: 'get',
  }),

  /** POST /client_companies */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/client_companies', {}, options),
    method: 'post',
  }),
}
