// Typelizer digest 1b3e213b445fe26f047419505cba1f9d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /home */
  home: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/home', {}, options),
    method: 'get',
  }),

  /** GET / */
  root: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/', {}, options),
    method: 'get',
  }),
}
