// Typelizer digest 8521556224bbc34e1b8900482e1d4b34
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export { default as Routes } from './RoutesController'
export { default as applications } from './ApplicationsController'
export { default as candidates } from './CandidatesController'
export { default as clientApplicationDecisions } from './Client/ApplicationDecisionsController'
export { default as clientApplications } from './Client/ApplicationsController'
export { default as clientCompanies } from './ClientCompaniesController'
export { default as dashboard } from './DashboardController'
export { default as identityEmailVerifications } from './Identity/EmailVerificationsController'
export { default as identityPasswordResets } from './Identity/PasswordResetsController'
export { default as jobPostings } from './JobPostingsController'
export { default as jobs } from './JobsController'
export { default as meetings } from './MeetingsController'
export { default as onboarding } from './OnboardingController'
export { default as organizationSelections } from './OrganizationSelectionsController'
export { default as organizations } from './OrganizationsController'
export { default as pipeline } from './PipelineController'
export { default as projects } from './ProjectsController'
export { default as sessions } from './SessionsController'
export { default as settingsEmails } from './Settings/EmailsController'
export { default as settingsPasswords } from './Settings/PasswordsController'
export { default as settingsProfiles } from './Settings/ProfilesController'
export { default as settingsSessions } from './Settings/SessionsController'
export { default as settingsTeams } from './Settings/TeamsController'
export { default as settingsWorkspaces } from './Settings/WorkspacesController'
export { default as sourcingBriefs } from './SourcingBriefsController'
export { default as tasks } from './TasksController'
export { default as users } from './UsersController'

import _applications from './ApplicationsController'
import _candidates from './CandidatesController'
import _clientApplications from './Client/ApplicationsController'
import _clientApplicationDecisions from './Client/ApplicationDecisionsController'
import _onboarding from './OnboardingController'
import _identityPasswordResets from './Identity/PasswordResetsController'
import _dashboard from './DashboardController'
import _identityEmailVerifications from './Identity/EmailVerificationsController'
import _jobs from './JobsController'
import _jobPostings from './JobPostingsController'
import _sourcingBriefs from './SourcingBriefsController'
import _meetings from './MeetingsController'
import _organizations from './OrganizationsController'
import _organizationSelections from './OrganizationSelectionsController'
import _sessions from './SessionsController'
import _Routes from './RoutesController'
import _settingsEmails from './Settings/EmailsController'
import _settingsPasswords from './Settings/PasswordsController'
import _settingsProfiles from './Settings/ProfilesController'
import _settingsTeams from './Settings/TeamsController'
import _settingsWorkspaces from './Settings/WorkspacesController'
import _users from './UsersController'
import _tasks from './TasksController'

export const application = _applications.update
export const candidate = _candidates.show
export const clientApplication = _clientApplications.show
export const clientApplicationDecision = _clientApplicationDecisions.create
export const completeOnboarding = _onboarding.complete
export const editCandidate = _candidates.edit
export const editIdentityPasswordReset = _identityPasswordResets.edit
export const home = _dashboard.home
export const identityEmailVerification = _identityEmailVerifications.show
export const identityPasswordReset = _identityPasswordResets.update
export const job = _jobs.show
export const jobPosting = _jobPostings.update
export const jobSourcingBrief = _sourcingBriefs.update
export const meeting = _meetings.update
export const newCandidate = _candidates.new
export const newIdentityPasswordReset = _identityPasswordResets.new
export const newOrganization = _organizations.new
export const onboardingProfile = _onboarding.profile
export const onboardingTeam = _onboarding.team
export const onboardingUseCases = _onboarding.useCases
export const onboardingWorkspace = _onboarding.workspace
export const organizationSelection = _organizationSelections.create
export const root = _dashboard.root
export const session = _sessions.destroy
export const settingsAppearance = _Routes.settingsAppearance
export const settingsEmail = _settingsEmails.show
export const settingsPassword = _settingsPasswords.show
export const settingsProfile = _settingsProfiles.show
export const settingsTeam = _settingsTeams.show
export const settingsWorkspace = _settingsWorkspaces.show
export const signIn = _sessions.new
export const signUp = _users.new
export const task = _tasks.update
