// Typelizer digest 71f71049f012e784c271fa5894472750
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /job_postings */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/job_postings', {}, options),
    method: 'post',
  }),

  /** PATCH /job_postings/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/job_postings/:id', params, options),
    method: 'patch',
  }),
}
