// Typelizer digest 8c055b1c3d483edd2d45f7adc14214ef
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /jobs */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/jobs', {}, options),
    method: 'get',
  }),

  /** POST /jobs */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/jobs', {}, options),
    method: 'post',
  }),

  /** GET /jobs/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/jobs/:id', params, options),
    method: 'get',
  }),

  /** PATCH /jobs/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/jobs/:id', params, options),
    method: 'patch',
  }),
}
