// Typelizer digest 076591c7bfc73b964bb589ace0d048d0
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /meetings */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/meetings', {}, options),
    method: 'get',
  }),

  /** POST /meetings */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/meetings', {}, options),
    method: 'post',
  }),

  /** PATCH /meetings/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/meetings/:id', params, options),
    method: 'patch',
  }),
}
