// Typelizer digest e5b118fb676f1b4e1a4aebce70f8d890
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /onboarding/profile */
  profile: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/onboarding/profile', {}, options),
    method: 'get',
  }),

  /** PATCH /onboarding/profile */
  updateProfile: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/onboarding/profile', {}, options),
    method: 'patch',
  }),

  /** GET /onboarding/workspace */
  workspace: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/onboarding/workspace', {}, options),
    method: 'get',
  }),

  /** POST /onboarding/workspace */
  createWorkspace: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/onboarding/workspace', {}, options),
    method: 'post',
  }),

  /** GET /onboarding/use-cases */
  useCases: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/onboarding/use-cases', {}, options),
    method: 'get',
  }),

  /** PATCH /onboarding/use-cases */
  updateUseCases: (options?: RouteOptions): RouteDefinition<'patch'> => ({
    url: buildUrl('/onboarding/use-cases', {}, options),
    method: 'patch',
  }),

  /** GET /onboarding/team */
  team: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/onboarding/team', {}, options),
    method: 'get',
  }),

  /** POST /onboarding/complete */
  complete: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/onboarding/complete', {}, options),
    method: 'post',
  }),
}
