// Typelizer digest 67f58e84400b2dce26fe57a756672444
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /organizations */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/organizations', {}, options),
    method: 'get',
  }),

  /** POST /organizations */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/organizations', {}, options),
    method: 'post',
  }),

  /** GET /organizations/new */
  new: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/organizations/new', {}, options),
    method: 'get',
  }),
}
