// Typelizer digest d714a73d6bbe2ac88c75013ef6b8f213
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** POST /organization_selection */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/organization_selection', {}, options),
    method: 'post',
  }),
}
