// Typelizer digest 219b0c92913ceeb5b63f7ef0d29c2a19
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /pipeline */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/pipeline', {}, options),
    method: 'get',
  }),
}
