// Typelizer digest 7ad7e16efaa793b837a92e48602bb9dd
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /projects */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/projects', {}, options),
    method: 'get',
  }),

  /** POST /projects */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/projects', {}, options),
    method: 'post',
  }),
}
