// Typelizer digest c0d1fa7200c21e96798c0b60010ea57e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** PATCH /jobs/:job_id/sourcing_brief */
  update: (
    params: { jobId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/jobs/:job_id/sourcing_brief', params, options),
    method: 'patch',
  }),

  /** POST /jobs/:job_id/sourcing_brief */
  create: (
    params: { jobId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/jobs/:job_id/sourcing_brief', params, options),
    method: 'post',
  }),
}
