// Typelizer digest 756a3ec79ff1b5b344e3979f2d979a84
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from './runtime'
import { buildUrl } from './runtime'

export default {
  /** GET /tasks */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/tasks', {}, options),
    method: 'get',
  }),

  /** POST /tasks */
  create: (options?: RouteOptions): RouteDefinition<'post'> => ({
    url: buildUrl('/tasks', {}, options),
    method: 'post',
  }),

  /** PATCH /tasks/:id */
  update: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'patch'> => ({
    url: buildUrl('/tasks/:id', params, options),
    method: 'patch',
  }),
}
