// Typelizer digest 2501ca4c5ca01912a8de91665a6b0462
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** POST /client/applications/:application_id/decision */
  create: (
    params: { applicationId: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'post'> => ({
    url: buildUrl('/client/applications/:application_id/decision', params, options),
    method: 'post',
  }),
}
