// Typelizer digest 5852a4a72709c072a975cbe78efab956
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { RouteDefinition, RouteOptions } from '../runtime'
import { buildUrl } from '../runtime'

export default {
  /** GET /client/applications */
  index: (options?: RouteOptions): RouteDefinition<'get'> => ({
    url: buildUrl('/client/applications', {}, options),
    method: 'get',
  }),

  /** GET /client/applications/:id */
  show: (
    params: { id: string | number } | string | number,
    options?: RouteOptions,
  ): RouteDefinition<'get'> => ({
    url: buildUrl('/client/applications/:id', params, options),
    method: 'get',
  }),
}
